version: '3.1'

services:
  #Frontend Service
  client:
    container_name: frontend_container
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    container_name: backend_container
    build: 
      context: ./server
    ports:
      - "5000:5000"
    